Correção de relatório

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -47,3 +47,16 @@ jobs:
             cypress/screenshots
             cypress/videos
             cypress/reports
+
+      - name: Debug mochawesome.json
+        run: cat cypress/reports/mochawesome/mochawesome.json || echo "File not found or empty"
+
+      - name: Ensure reports directory exists
+        run: mkdir -p cypress/reports/mochawesome
+
+      - name: Merge reports
+        run: |
+          if ! npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/report.json; then
+            echo "Failed to merge reports. Creating an empty report."
+            echo '{}' > cypress/reports/mochawesome/report.json
+          fi
